version: 0.0
os: linux
files:
  - source: /
    destination: /home/iconnect/iconnect-main/
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
