version: 0.0
os: linux
files:
  - source: /
    destination: /home/iconnect/iconnect-main/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: stop-application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
