version: 0.0
os: linux
files:
  - source: /
    destination: /home/iconnect/iconnect-main/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
