version: 0.0
os: linux
files:
  - source: /
    destination: /home/iconnect/iconnect-main/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
