version: '3'

services:
  iconnect:
    container_name: iconnect
    image: iconnect:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    env_file:
      - .env
    restart: unless-stopped