version: "3"

services:
  iconnect:
    container_name: iconnect
    image: iconnect:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    env_file:
      # - .env
      - envTarget=${envTarget}
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - /home/iconnect/storage/:/home/iconnect/storage/
    restart: unless-stopped
