server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user}
    username: ${DB_USERNAME:iconnect_user}
    password: ${DB_PASSWORD:P@ssw0rd}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

iconnect:
  app:
    jwtSecret: ${JWT_SECRET:Y2whcXUzanZ2dHMzY3IzdA==}
    jwtAccessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION:600000} # 1 minute
    jwtRefreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION:86400000} # 1 day
