server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://connect-test-db.czvuahdk39ku.eu-west-1.rds.amazonaws.com:5432/postgres}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:jw8s0F4}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

iconnect:
  app:
    jwtSecret: Y2whcXUzanZ2dHMzY3IzdA==
    jwtExpiration: 86400 # 1 day
