server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

iconnect:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtAccessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    jwtRefreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
