server:
  port: 8686

spring:
  application:
    name: iconnectBackEnd
  datasource:
    url: jdbc:postgresql://connect-test-db.czvuahdk39ku.eu-west-1.rds.amazonaws.com:5432/postgres
    username: 'dev'
    password: 'jw8s0F4'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      show-sql: 'true'
iconnect:
  app:
    jwtSecret: Y2whcXUzanZ2dHMzY3IzdA==
 #24 Hours
    jwtExpiration: 86400