server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: iconnectBackEnd
  datasource:
    url: jdbc:postgresql://localhost:5432/iconnect
    username: 'iconnect_user'
    password: 'P@ssw0rd'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'